import oracledb
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

# Tentar carregar do Streamlit secrets primeiro, depois do .env
try:
    import streamlit as st
    DB_USER = st.secrets.get("DB_USER", os.getenv("DB_USER"))
    DB_PASSWORD = st.secrets.get("DB_PASSWORD", os.getenv("DB_PASSWORD"))
    DB_DSN = st.secrets.get("DB_DSN", os.getenv("DB_DSN"))
except (ImportError, FileNotFoundError):
    # Fallback para .env quando não estiver no Streamlit
    load_dotenv()
    DB_USER = os.getenv("DB_USER")
    DB_PASSWORD = os.getenv("DB_PASSWORD")
    DB_DSN = os.getenv("DB_DSN")

def get_connection():
    """
    Estabelece uma conexão com o banco de dados Oracle usando oracledb.
    """
    try:
        if not all([DB_USER, DB_PASSWORD, DB_DSN]):
            raise ValueError("Credenciais do banco de dados não encontradas nas variáveis de ambiente.")
            
        connection = oracledb.connect(
            user=DB_USER,
            password=DB_PASSWORD,
            dsn=DB_DSN
        )
        return connection
    except Exception as e:
        print(f"Erro ao conectar ao Oracle DB: {e}")
        return None

def get_engine():
    """
    Cria uma engine SQLAlchemy para o banco de dados Oracle.
    """
    try:
        if not all([DB_USER, DB_PASSWORD, DB_DSN]):
            raise ValueError("Credenciais do banco de dados não encontradas nas variáveis de ambiente.")
        
        # Formato da string de conexão para oracledb
        connection_string = f"oracle+oracledb://{DB_USER}:{DB_PASSWORD}@{DB_DSN}"
        engine = create_engine(connection_string)
        return engine
    except Exception as e:
        print(f"Erro ao criar engine SQLAlchemy: {e}")
        return None

def create_table():
    """
    Cria a tabela FARM_DATA se ela não existir.
    """
    conn = get_connection()
    if not conn:
        return

    cursor = conn.cursor()
    try:
        cursor.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE FARM_DATA (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    soil_humidity NUMBER,
                    ph_level NUMBER,
                    temperature NUMBER,
                    rainfall NUMBER,
                    nitrogen NUMBER,
                    phosphorus NUMBER,
                    potassium NUMBER,
                    crop_yield NUMBER,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """)
        print("Tabela FARM_DATA criada ou já existente.")
    except Exception as e:
        print(f"Erro ao criar tabela: {e}")
    finally:
        cursor.close()
        conn.close()

def insert_data(df):
    """
    Insere dados de um DataFrame na tabela FARM_DATA.
    """
    conn = get_connection()
    if not conn:
        return

    cursor = conn.cursor()
    data_tuples = [tuple(x) for x in df.values]
    
    sql = """
        INSERT INTO FARM_DATA (soil_humidity, ph_level, temperature, rainfall, nitrogen, phosphorus, potassium, crop_yield)
        VALUES (:1, :2, :3, :4, :5, :6, :7, :8)
    """
    
    try:
        cursor.executemany(sql, data_tuples)
        conn.commit()
        print(f"Inseridas {len(data_tuples)} linhas.")
    except Exception as e:
        print(f"Erro ao inserir dados: {e}")
    finally:
        cursor.close()
        conn.close()

def fetch_data():
    """
    Busca todos os dados da tabela FARM_DATA usando SQLAlchemy.
    """
    engine = get_engine()
    if not engine:
        return pd.DataFrame()

    try:
        # Excluir created_at para evitar problemas de serialização Arrow no Streamlit
        query = """
            SELECT id, soil_humidity, ph_level, temperature, rainfall, 
                   nitrogen, phosphorus, potassium, crop_yield 
            FROM FARM_DATA
        """
        # Usando a engine com read_sql para remover o Warning do pandas `only supports SQLAlchemy connectable`
        df = pd.read_sql(query, engine)
        df.columns = df.columns.str.lower()
        return df
    except Exception as e:
        print(f"Erro ao buscar dados: {e}")
        return pd.DataFrame()
